export enum EntityType {
  PLAYER = "PLAYER",
  GEM = "GEM",
  GEM_BUNDLE = "GEM_BUNDLE",
  ROCK = "ROCK",
  SOIL = "SOIL",
  EARTH = "EARTH",
  BLIMP = "BLIMP",
  AD = "AD",
  PARALLAX_SPRITE = "PARALLAX_SPRITE",
  TROPHY = "TROPHY",
  GEM_BANK = "GEM_BANK",
  OTHER = "OTHER"
}
