export enum EntityType {
  PLAYER = "PLAYER",
  GEM = "GEM",
  GEM_BUNDLE = "GEM_BUNDLE",
  ROUND_ROCK = "ROUND_ROCK",
  SQUARE_ROCK = "SQUARE_ROCK",
  WALL = "WALL",
  METAL_WALL = "METAL_WALL",
  SOIL = "SOIL",
  EARTH = "EARTH",
  AD = "AD",
  BLIMP = "BLIMP",
  BILLBOARD = "BILLBOARD",
  PARALLAX_SPRITE = "PARALLAX_SPRITE",
  TROPHY = "TROPHY",
  GEM_BANK = "GEM_BANK",
  RESPAWN_AREA = "RESPAWN_AREA",
  OTHER = "OTHER"
}
