// Keep this up to date
export enum PinataApiErrorCode {
  UNKNOWN_ERROR = 0,
  INTERNAL_ERROR = 100,
  EMAIL_ADDRESS_ALREADY_EXISTS = 110,
  USER_NAME_ALREADY_EXISTS = 120,
  INVALID_EMAIL_ADDRESS = 130,
  INVALID_USER_NAME = 140,
  NOT_AUTHORISED = 150,
  AUTHENTICATION_FAILURE = 160,
  INVALID_REQUEST_BODY = 170,
  MISSING_ARGUMENT = 180,
  NOT_FOUND = 190
}
